services: 
  
  api: 
    build: "./src/Sample.Rabbit.Api"
    ports: 
      - "8000:5000"
  
  worker: 
    build: "./src/Sample.Rabbit.Worker"
    ports: 
      - "8000:5001"
  
  jaeger: 
    image: "jaegertracing/all-in-one:latest"
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  
  rabbitmq: 
    image: masstransit/rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
  
version: "3.8"
